name: Sync to Personal Repo

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add personal repo remote
        run: |
          git remote add personal https://${{ secrets.PAT_TOKEN }}@github.com/sanjeet-v/gitapro.git

      - name: Verify remote
        run: git remote -v

      - name: Push to personal repo
        run: |
          git push -f personal main
